### ISSUE TITLE
This project does not seem to adhere to GNU AGPL v3...

### ISSUE THREAD

**Issue by sebras** [Garyzx/Android-MuPDF_as#1]
This project appears to contain a compiled copy of MuPDF from https://mupdf.com/ which is released under a GNU AGPL v3. The project your [forked](https://github.com/joniks/Android-MuPDF) has a COPYING file specifying it is released under GNU AGPL v3, and it [links](https://github.com/joniks/Android-MuPDF/blob/master/README.md) to the exact commit of the source code used to build the native libraries. When your project does the same I believe it is less likely you will end up with someone claiming you might not adhere to AGPL. If you cannot adhere to GNU AGPL v3 for some reason you might be in violation of the license and it might be best for you to remove MuPDF entirely from your project.

**Comment by lihezx** [comment]
Done
